version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          command: npm install

      - save_cache:
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          command: npm test
          
      - run:
          name: Build
          command: npm build
      
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  Build and Deploy:
    jobs:
      - build